### ISSUE TITLE
Running client and server on different systems

### ISSUE THREAD

**Issue by Shivansh20128** [JorisHerbots/vegvisir#10]
Hi,
I am doing an experiment in which I need to use the setup for the client-shaper-server, where the client and the server need to be on a separate system (the client and the shaper can coexist on the same system). While going through the scripts inside the repository, I found a file (tc-netem-shaper/scenarios/bba_buffering_paper.sh) where the interfaces and the IPs are mentioned for the network simulation. Please advise if it is possible to do so by making some changes to the existing setup configuration and provide some helpful information to achieve that. 
Thank You

**Comment by Shivansh20128** [comment]
I went through the code to understand the flow of vegvisir.  From what I understood, if I make changes in the docker-compose file, like adding a new docker overlay network that will allow containers from different hosts to join (with the help of a docker swarm), and accordingly change the networks for client and server, I can run vegvisir with client and server on different systems. I am doing this in connection with the project [cross that boundary](https://github.com/EDM-Research/cross-that-boundary-mmsys23-nossdav ). 
But first, I want to ask you if you think this would work. 
Another question that I have about the docker-compose file is that there are many services running, like sim (which I think is the shaper service), server, client, tcpdump_leftnet, tcpdump_rightnet, iperf_client, iperf_server, and networks. Could you say a line or two about each of them? Because I need to understand what they refer to before changing them.

**Comment by JorisHerbots** [comment]
> I went through the code to understand the flow of vegvisir. From what I understood, if I make changes in the docker-compose file, like adding a new docker overlay network that will allow containers from different hosts to join (with the help of a docker swarm), and accordingly change the networks for client and server, I can run vegvisir with client and server on different systems. I am doing this in connection with the project [cross that boundary](https://github.com/EDM-Research/cross-that-boundary-mmsys23-nossdav).

As long as your changes cause traffic to flow over the shaper, you achieve the same goal Vegvisir has.

>But first, I want to ask you if you think this would work. Another question that I have about the docker-compose file is that there are many services running, like sim (which I think is the shaper service), server, client, tcpdump_leftnet, tcpdump_rightnet, iperf_client, iperf_server, and networks. Could you say a line or two about each of them? Because I need to understand what they refer to before changing them.

- `server` hosts the server software
- `client` hosts the client software
- `sim` hosts the  shaper software
- `tcpdump_leftnet` and `tcpdump_rightnet` are containers that copy the network stack from `sim` to monitor traffic flowing between the left- and rightnet; as per the [docs](https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode), these will not work in a Docker Swarm deployment
- `iperf_client` and `iperf_server` are remains from the [QIR](https://github.com/quic-interop/quic-interop-runner) and (currently) unused
