### ISSUE TITLE
No metrics_log.txt file found

### ISSUE THREAD

**Issue by Jazkiel** [JorisHerbots/vegvisir#13]
I keep getting this error while running python -m vegvisir run paper_experiment_full.json

Info > Running godashcl over tc-netem-cl against quic-go
Traceback (most recent call last):
  File "/home/ubuntu/root1/vegvisir/./util/segmentGraph.py", line 39, in <module>
    with open(logFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/root1/vegvisir/logs/cross_layer_paper/2023-11-06T_10-21-48/godashcl-bba2cl-double-bbb-2s__tc-netem-cl-paper__quic-go/client/metrics_log.txt'
Traceback (most recent call last):
  File "/home/ubuntu/root1/vegvisir/./util/segmentGraph.py", line 39, in <module>
    with open(logFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/root1/vegvisir/logs/cross_layer_paper/2023-11-06T_10-21-48/godashcl-bba2cl-double-bbb-2s__tc-netem-cl-paper__quic-go/client/metrics_log.txt'
Traceback (most recent call last):
  File "/home/ubuntu/root1/vegvisir/./util/segmentGraph.py", line 39, in <module>
    with open(logFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/root1/vegvisir/logs/cross_layer_paper/2023-11-06T_10-21-48/godashcl-bba2cl-double-bbb-2s__tc-netem-cl-paper__quic-go/client/metrics_log.txt'
Error > ITU P.1203 step failed [Errno 2] No such file or directory: '/home/ubuntu/root1/vegvisir/logs/cross_layer_paper/2023-11-06T_10-21-48/godashcl-bba2cl-double-bbb-2s__tc-netem-cl-paper__quic-go/client/files'

**Comment by Shivansh20128** [comment]
Hi,
I am also getting this error. How did it get resolved?

**Comment by Jazkiel** [comment]
@Shivansh20128 The dataset folders should be named 2sec,4sec,6sec instead of 2s,4s,6s. I think that's a typo in the README

**Comment by Shivansh20128** [comment]
ohh okay. Thank you. But I think there is some other issue with my system.
But I will keep that in mind.

**Comment by JorisHerbots** [comment]
> @Shivansh20128 The dataset folders should be named 2sec,4sec,6sec instead of 2s,4s,6s. I think that's a typo in the README

Thanks for reporting. Fixed in https://github.com/EDM-Research/cross-that-boundary-mmsys23-nossdav/commit/22e726573ccd739d6586478edd3e393626bc64fd
