### ISSUE TITLE
metrics_log.txt file not found

### ISSUE THREAD

**Issue by Shivansh20128** [JorisHerbots/vegvisir#14]
Hi,
I have been using vegvisir for some time now for some experiments. But then it started breaking on my system. So, I made a fresh installation on a Ubuntu 22.04 PC having Python 3.10.12. I followed all the steps correctly, but still when I run vegvisir using the command "python -m vegvisir run paper_experiment_full.json", I get this error.

Vegvisir > Enter password to run sudo commands: 
Info > Running godashcl over tc-netem-cl against quic-go
Info > TimeoutSensor detected client exit before timeout, halting timer. Ran for 1 seconds.
Info > Test run duration: 0:00:02.409318
Traceback (most recent call last):
  File "/home/shivansh/root/vegvisir/./util/segmentGraph.py", line 39, in <module>
    with open(logFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shivansh/root/vegvisir/logs/cross_layer_paper/2023-11-10T_11-53-39/godashcl-bba2cl-double-bbb-2s__tc-netem-cl-paper__quic-go/client/metrics_log.txt'
Traceback (most recent call last):
  File "/home/shivansh/root/vegvisir/./util/segmentGraph.py", line 39, in <module>
    with open(logFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shivansh/root/vegvisir/logs/cross_layer_paper/2023-11-10T_11-53-39/godashcl-bba2cl-double-bbb-2s__tc-netem-cl-paper__quic-go/client/metrics_log.txt'
Traceback (most recent call last):
  File "/home/shivansh/root/vegvisir/./util/segmentGraph.py", line 39, in <module>
    with open(logFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shivansh/root/vegvisir/logs/cross_layer_paper/2023-11-10T_11-53-39/godashcl-bba2cl-double-bbb-2s__tc-netem-cl-paper__quic-go/client/metrics_log.txt'
Info > Vegvisir experiment finished. Total elapsed time 0:00:17.695305

Any reason why this might be happening?
Thanks

**Comment by JorisHerbots** [comment]
This is not a bug/error in Vegvisir itself.
The setup from https://github.com/EDM-Research/cross-that-boundary-mmsys23-nossdav causes the error.

Could you provide the details from the `output.txt `log and your experiment JSON? These will provide us with more insights as to what might be failing. From the small log you posted, I can see that the client is exiting quickly, which indicates that it did not start up properly. This causes the errors about `metrics_log.txt` since this output file is never generated during an experiment due to the client not starting.

**Comment by Shivansh20128** [comment]
I just saw the output.txt file and noticed that the containers were unable to start due to permission issues. So I ran vegvisir with sudo privileges with the command "sudo python -m vegvisir run paper_experiment_full.json".
So now the containers were able to start, but the error was still there.

Vegvisir > Enter password to run sudo commands: 
Info > Running godashcl over tc-netem-cl against quic-go
Info > TimeoutSensor detected client exit before timeout, halting timer. Ran for 4 seconds.
Info > Test run duration: 0:00:35.116946
Traceback (most recent call last):
  File "/home/shivansh/root/vegvisir/./util/segmentGraph.py", line 39, in <module>
    with open(logFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shivansh/root/vegvisir/logs/cross_layer_paper/2023-11-10T_18-54-34/godashcl-bba2cl-double-bbb-2s__tc-netem-cl-paper__quic-go/client/metrics_log.txt'
Traceback (most recent call last):
  File "/home/shivansh/root/vegvisir/./util/segmentGraph.py", line 39, in <module>
    with open(logFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shivansh/root/vegvisir/logs/cross_layer_paper/2023-11-10T_18-54-34/godashcl-bba2cl-double-bbb-2s__tc-netem-cl-paper__quic-go/client/metrics_log.txt'
Traceback (most recent call last):
  File "/home/shivansh/root/vegvisir/./util/segmentGraph.py", line 39, in <module>
    with open(logFile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/shivansh/root/vegvisir/logs/cross_layer_paper/2023-11-10T_18-54-34/godashcl-bba2cl-double-bbb-2s__tc-netem-cl-paper__quic-go/client/metrics_log.txt'
Error > ITU P.1203 step failed [Errno 2] No such file or directory: '/home/shivansh/root/vegvisir/logs/cross_layer_paper/2023-11-10T_18-54-34/godashcl-bba2cl-double-bbb-2s__tc-netem-cl-paper__quic-go/client/files'
Info > Vegvisir is waiting for 4 post-hook processor(s) to stop. If this message persists, perform CTRL + C
Info > Vegvisir experiment finished. Total elapsed time 0:00:45.357102

I am adding the output.txt file from this run and the experiment JSON, too. Rest assured that I have not made any changes in the code, and this is a fresh installation. I have just reduced the number of tests in the experiment JSON.
[experiment.json](https://github.com/JorisHerbots/vegvisir/files/13319804/experiment.json)
[output.txt](https://github.com/JorisHerbots/vegvisir/files/13319805/output.txt)

**Comment by JorisHerbots** [comment]
Running Vegvisir with sudo is an unsupported use case that might trigger undefined behavior. Please configure docker so it works without root privileges as detailed in the installation guide: https://docs.docker.com/engine/install/linux-postinstall/

Then, could you retry the experiment and see if the errors persist? From the output log, I can confirm that the goDASH client is starting but not streaming anything. Can you ensure the path `/home/shivansh/root/datasets/BigBuckBunny/2sec/` exists and contains the correct dataset?

**Comment by Shivansh20128** [comment]
The dataset path was set wrong.
Resolved now.
